language: php

php:
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer clearcache
 - composer install --ignore-platform-reqs

script:
 - ./vendor/bin/phpstan analyze --no-progress

notifications:
 email: false
