name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        include:
          - php: 7.2.34
            phpstan-config: php7
          - php: 7.3.25
            phpstan-config: php7
          - php: 7.4.13
            phpstan-config: php7
          - php: 8.0.1
            phpstan-config: php8

    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/php
          key: php-build-${{ matrix.php }}

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/php-build/php-build.git
          cd php-build
          ./install-dependencies.sh
          export CFLAGS="$CFLAGS -march=x86-64"
          export CXXFLAGS="$CXXFLAGS -march=x86-64"
          ./bin/php-build "${{ matrix.php }}" "$GITHUB_WORKSPACE/php"
          
      - name: Prefix PHP to PATH
        run: echo $GITHUB_WORKSPACE/php/bin >> $GITHUB_PATH

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress -c phpstan.${{ matrix.phpstan-config }}.neon
